= Demo app on ARO

. List the containers that are in Azure Blob Storage for us to use.
+
[source,sh,role=execute]
----
az storage container list --auth-mode login --account-name ostoystorage${GUID} --query '[].name' -o tsv
----

. Create a secret for Kubernetes to use to access the Key Vault. When this command is executed, the Service Principal’s credentials are stored in the secrets-store-creds Secret object, where it can be used by the Secret Store CSI driver to authenticate with Azure Key Vault and retrieve secrets when needed.
+
[source,sh,role=execute]
----
oc create secret generic secrets-store-creds \
-n $PROJECT_NAME \
--from-literal clientid=$SERVICE_PRINCIPAL_CLIENT_ID \
--from-literal clientsecret=$SERVICE_PRINCIPAL_CLIENT_SECRET
----

. Create a label for the secret. By default, the secret store provider has filtered watch enabled on secrets. You can allow it to find the secret in the default configuration by adding this label to the secret.
+
[source,sh,role=execute]
----
oc -n $PROJECT_NAME label secret secrets-store-creds secrets-store.csi.k8s.io/used=true
----

. Create the Secret Provider Class to give access to this secret. To learn more about the fields in this class see https://learn.microsoft.com/en-us/azure/aks/hybrid/secrets-store-csi-driver#create-and-apply-your-own-secretproviderclass-object[SecretProviderClass] object.
+
[source,sh,role=execute]
----
cat <<EOF | oc apply -f -
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname
  namespace: $PROJECT_NAME
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    userAssignedIdentityID: ""
    keyvaultName: "${KEYVAULT_NAME}"
    objects: |
      array:
        - |
          objectName: connectionsecret
          objectType: secret
          objectVersion: ""
    tenantId: "${AZURE_TENANT_ID}"
EOF
----

. Deploy the application. First deploy the microservice.
+
[source,sh,role=execute]
----
oc apply -n $PROJECT_NAME -f ${HOME}/ostoy-microservice-deployment.yaml
----

. Then the front end.
+
[source,sh,role=execute]
----
oc apply -n $PROJECT_NAME -f ${HOME}/ostoy-frontend-deployment.yaml
----

. Get the route for the newly deployed application.
+
[source,sh,role=execute]
----
oc get route ostoy-route -o jsonpath='{.spec.host}{"\n"}' -n ${PROJECT_NAME}
----

. Click on "ASO - Blob Storage" in the left menu and enter some files and content to store to AWS Blob Storage.

. Now to confirm that this is not just some smoke and mirrors, let's confirm directly via the CLI. Run the following to list the contents of our Blob Storage.
+
[source,sh,role=execute]
----
az storage blob list --account-name ostoystorage${GUID} --connection-string $CONNECTION_STRING -c ${PROJECT_NAME}-container --query "[].name" -o tsv
----

. Open an interactive shell session inside the container within our pod.
+
[source,sh,role=execute]
----
oc rsh $(oc get pods -o name | grep frontend)
----

. If you remember, in our deployment manifest we defined the mount location as `/mnt/secrets-store`:
+
[source,yaml,options=nowrap]
----
[...]
volumeMounts:
- name: configvol
  mountPath: /var/config
- name: secretvol
  mountPath: /var/secret
- name: datavol
  mountPath: /var/demo_files
- name: secrets-store-inline
  mountPath: "/mnt/secrets-store"
  readOnly: true
[...]
----

. Open the file to see the ConnectionSecret. 
+
[source,sh,role=execute]
----
cat /mnt/secrets-store/connectionsecret; echo
----
+
[NOTE]
====
Remember, you are able to view this because you are logged in as kube:admin.
====

. Exit the session
+
[source,sh,role=execute]
----
exit
----


